### ISSUE TITLE
[Bug] Crash with Electroblob's Wizardry

### ISSUE THREAD

**Issue by brisingraerowing** [ben-mkiv/OCDevices#10]
**Describe the bug**
Crash on startup with EB Wizardry

**To Reproduce**
1. Start with OCDevices and Electroblob's Wizardry
2. ...
3. Crash

**Expected behavior**
Game starts without issue.

**Screenshots / Code Snippet**
N/A

**Minecraft:**
 - Mod Version 1.0.0-43
 - Minecraft Version 1.12.2
 - Forge Version 14.23.5.2847

**Additional context**
[Crash Log](https://paste.dimdev.org/ocewixopuc.mccrash)

**Comment by ben-mkiv** [comment]
i've opened a bug report on the repo of wizardry as the only way to fix this for me would be a blacklist of their items...

https://github.com/Electroblob77/Wizardry/issues/288

**Comment by ben-mkiv** [comment]
Here's a build which catches the NPE and allows you to start with OCDevices and Wizardry installed, i'll upload an official build to curseForge in the next days.

Actually the nanoAnalyzer function cant be used on Wizardry items, where the fix is up to electroblob.

http://ci.pc-logix.com/job/OCDevices/44/artifact/build/libs/ocdevices-MC1.12.2-1.0.0-44.jar

And thanks for reporting the issue :)

**Comment by ben-mkiv** [comment]
1.0.0-44 is on curseForge now.

Closing this issue as i cant do anymore on my side.
