### ISSUE TITLE
[Bug] Cannot Start Game / 1.0.0-29 and OpenGlasses2

### ISSUE THREAD

**Issue by nephatrine** [ben-mkiv/OCDevices#9]
**Describe the bug**
Get a duplicate mod error when starting game with OCDevices pre-release and OpenGlasses. OCDevices contains a library Commons0815-MC1.12.2-1.0.3.jar while OpenGlasses contains Commons0815-MC1.12.2-1.1.2.jar. As these are both OpenComputers addons, it would be neat to use them both.

The snapshot version from CurseForge does not have this issue as it does not embed that library at all, but I had wanted to play with some of the new things you've added.

**To Reproduce**
1. Install latest OpenGlasses2 and OCDevices.
2. Start Game.

**Expected behavior**
Play game with both.

**Minecraft:**
- ocdevices-MC1.12.2-1.0.0-29.jar
- OpenGlasses-MC1.12.2-2.2-36.jar

**Comment by ben-mkiv** [comment]
sorry for the late reply, didnt get a mail notification about the issue.

i've uploaded a new alpha build to curseForge, but please remove all content of your OCDevices Cases before updating, as it might corrupt existing case blocks in the world due to new data structure which was necessary for case upgrades

**Comment by ben-mkiv** [comment]
from now on the lib is a separate file/project 
https://www.curseforge.com/minecraft/mc-mods/commons0815

If you use Twitch Client it will auto download the necessary dependency.

This should avoid conflicts in the future :)

**Comment by nephatrine** [comment]
Just wanted to pop in and say thanks.
